### ISSUE TITLE
Epub3 Export Icon

### ISSUE THREAD

**Issue by unit29868** [unit29868/pressbooks#11]
Create a new EPUB3 icon for the Exports interface.

**Comment by bdolor** [comment]
@hughmcguire — does PB have design resources that could be used for this ticket? I can do it, but there are better designers than me out there.

**Comment by hughmcguire** [comment]
We can do it! ... end of the week?

On Mon, Dec 2, 2013 at 4:56 PM, Brad notifications@github.com wrote:

> @hughmcguire https://github.com/hughmcguire — does PB have design
> resources that could be used for this ticket? I can do it, but there are
> better designers than me out there.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unit29868/pressbooks/issues/11#issuecomment-29661920
> .

## 

---

hughmcguire.net | twitter.com/hughmcguire

## skype. h.mcguire | tel. +1.514.464.2047

**Comment by bdolor** [comment]
sure thing...thank you!

**Comment by bdolor** [comment]
@hughmcguire — what's the status of this one?

**Comment by hughmcguire** [comment]
designer had to be away from work for personal reasons, just back at work
now.... will check in about this specifically.

On Thu, Dec 12, 2013 at 4:12 PM, Brad notifications@github.com wrote:

> @hughmcguire https://github.com/hughmcguire — what's the status of this
> one?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unit29868/pressbooks/issues/11#issuecomment-30462233
> .

## 

---

hughmcguire.net | twitter.com/hughmcguire

## skype. h.mcguire | tel. +1.514.464.2047

**Comment by bdolor** [comment]
new icons added in https://github.com/unit29868/pressbooks/pull/37 ... closing
