### ISSUE TITLE
Update and verify HTMLawed

### ISSUE THREAD

**Issue by unit29868** [unit29868/pressbooks#19]
To prevent HTML5 tags from being culled by tidy, I ended up editing htmlawed beta to provide some limited support for this, and pass additional information into the routine from the EPUB3 class with the $spec variable, seen here:

https://github.com/unit29868/pressbooks/blob/dev/includes/modules/export/epub3/class-pb-epub3.php#L68

At this time I do not know if there will be htmlawed compatiability issues between the EPUB2/3 versions.

**Comment by bdolor** [comment]
updated htmLawed to 1.2.beta.4 https://github.com/unit29868/pressbooks/commit/7240101d90924047db156b0a2aa0834c690effef
