### ISSUE TITLE
Move Audio/Video/Image Methods into single Asset scrape function

### ISSUE THREAD

**Issue by unit29868** [unit29868/pressbooks#2]
Class-pb-epub201.php now stores assets in a directory called /assets/; formerly /images/

The audio and video methods scrapeAndKneadAudios() and scrapeAndKneadVideos() alongside scrapeAndKneadImages() Should be lumped into a scrapeAndKneadAssets() method so that more types of media can be easily supported moving forward.

**Comment by bdolor** [comment]
amalgamated `scrapeAndKneadAudios()`, `scrapeAndKneadVideos()` into `scrapeAndKneadMedia()`. 

`scrapeAndKneadImages()` will be left as is — it's functionality is specific to images (validation and whatnot) and cannot/should not be brought into a `scrapeAndKneadAssets()` function
