### ISSUE TITLE
Decision on file/directory structure for epub3

### ISSUE THREAD

**Issue by bdolor** [unit29868/pressbooks#20]
This is related to issue #18 — I recommended putting audio and video files in the assets directory which I now understand to be contrary to what is recommended by authorities on the issue, although it doesn't contravene any specific specifications as far as I can tell.

Reference: 
http://www.idpf.org/epub/30/spec/epub30-ocf.html#sec-container-file-and-dir-structure

Argument for keeping it as is in #18
"All other files within the OCF Abstract Container may be in any location descendant from the container's root directory except within the META-INF directory."

Argument for changing the direction to images, audio and video each being a directory of their own:
"It is recommended that the contents of each of the individual Publications be stored within its own dedicated directory under the container's root."

thoughts?

**Comment by dac514** [comment]
I don't think they are talking about assets when they say Publications. That is, at the top of the same document:

" EPUB Open Container Format (OCF) 3.0, defines a file format and processing model for encapsulating the sets of related resources that comprise one or more EPUB® Publications into a single-file container."

Publications meaning EPUB here, not assets. I don't see us packaging more than one EPUB inside an EPUB? This might sound like a Xzibit meme, but that's kind of how it is if you unpack a mobi file, multiple mobi files (and an epub) inside the mobi file, and I think that's what they are on about.

My vote is, If it validates with epubcheck then keep it as simple as possible.

Cheers.

**Comment by dac514** [comment]
Or maybe I don't understand the question? 

Anyway, my answer will always be "1) It validates 2) Make it easier to make changes later, with a focus on less code later, not now."

Feel free to interpret however you want. I will accept any work done.

**Comment by bdolor** [comment]
My understanding is they are talking about resources of the publication (epub) and the recommended file and directory structure. 'Assets' were mentioned only because that's the name of the directory where images now go in class epub201. Since we are now inheriting from epub201, it would be easier to use the same directory structure, otherwise we have to override the functions that specify where to put 'publication resources', or video, audio and image files. In order to stick close to the recommendations, it would require modifying epub201 to put images in a directory called 'images' instead of 'assets'.

**Comment by unit29868** [comment]
I spent a little time goggling this topic, and I can't find a single good reason not to utilize a directory hierarchy under assets.

I think it's safe to proceed with going the route of `/OEBPS/assets/images`, `/OEBPS/assets/audio`, etc.

**Comment by dac514** [comment]
Sounds good to me. Please refactor with path names in constructor (or properties) like you did with $this->filext, so it's not spread all over the place like it was before.

**Comment by bdolor** [comment]
closing, leaving recommendations as is in #18
