### ISSUE TITLE
Extend Class Epub3 from Epub201

### ISSUE THREAD

**Issue by unit29868** [unit29868/pressbooks#3]
Epub3 class should extend Epub201, not extend Export and duplicate Epub201 functionality. Then, extend the bare minimum to support Epub3

**Comment by bdolor** [comment]
Initiated a pull request —

**Comment by unit29868** [comment]
Since @bdolor addressed this, I'll mark this issue as closed and fold related issues into the 'culling redundant functionality between Epub2 and Epub3 modules; issue.
