### ISSUE TITLE
MathML

### ISSUE THREAD

**Issue by unit29868** [unit29868/pressbooks#38]
Limited MathML support is specified in the EPUB3 spec (http://www.idpf.org/epub/30/spec/epub30-contentdocs.html#sec-xhtml-mathml), Safari (mediocre) and Firefox (pretty good) offer support for MathML natively, but Google evidently doesn’t find it worth supporting, and dropped native rendering support for it from Chrome. They sight security and speed concerns primarily (http://news.cnet.com/8301-1023_3-57610854-93/google-subtracts-mathml-from-chrome-and-anger-multiplies/). Google recommends using an intermediate JavaScript library called MathJax (http://www.mathjax.org/).

As our primary window into this content creation and management system is the browser, I’ll work towards embedding MathJax into Pressbooks and getting it through the export chain into EPUB3 format.

In case you’re unfamiliar, writing MathML is about on the level of writing straight HTML, if not more confusing. You can see examples of the syntax here (http://en.wikipedia.org/wiki/MathML).

**Comment by unit29868** [comment]
I found a Mathjax extention for Wordpress to use as a basis: http://wordpress.org/plugins/mathjax-latex/

This particular plugin is setup to allow math in posts expressed using the latex syntax. I installed it on my site and edited it to use a local Mathjax installation configured to accept MathML syntax as well. Below is a screenshot of my Pressbooks test site with MathML.
![mathmlpressbooks](https://f.cloud.github.com/assets/4621207/1859592/25aa88ae-77a6-11e3-9a8a-0262941f9e5d.png)

My current todo is to get the MathML syntax tags exported into the Epub3 file (currently getting parsed out of post content).

**Comment by hughmcguire** [comment]
nice.

On Tue, Jan 7, 2014 at 9:16 AM, unit29868 notifications@github.com wrote:

> I found a Mathjax extention for Wordpress to use as a basis:
> http://wordpress.org/plugins/mathjax-latex/
> 
> This particular plugin is setup to allow math in posts expressed using the
> latex syntax. I installed it on my site and edited it to use a local
> Mathjax installation configured to accept MathML syntax as well. Below is a
> screenshot of my Pressbooks test site with MathML.
> [image: mathmlpressbooks]https://f.cloud.github.com/assets/4621207/1859592/25aa88ae-77a6-11e3-9a8a-0262941f9e5d.png
> 
> My current todo is to get the MathML syntax tags exported into the Epub3
> file (currently getting parsed out of post content).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unit29868/pressbooks/issues/38#issuecomment-31740303
> .

## 

---

hughmcguire.net | twitter.com/hughmcguire

## skype. h.mcguire | tel. +1.514.464.2047

**Comment by unit29868** [comment]
For testing I decided to comment out the htmlawed tidy routine and export my test epub 3 book with MathML samples and see how things go. Both Azardi and iBooks seemed ok with the result. Will look into the encode/decode approach @bdolor mentioned in issue #41 to work around the htmlawed culling.

![mathml_ibooks](https://f.cloud.github.com/assets/4621207/1878044/0a8f437c-7934-11e3-9e68-be3daffa7fc5.jpg)

**Comment by unit29868** [comment]
MathML export capability is now checked into the repository. Test files validate with epubcheck. Supporting Wordpress plugins used for this:
Mathjax-latex: http://wordpress.org/plugins/mathjax-latex/
Preserved-HTML-Editor-Markup: http://wordpress.org/plugins/preserved-html-editor-markup/

It is worth mentioning the editor plugin isn't an ideal solution for the long term. Investigating a better way to prevent the editor from mangling the post code is a worthwhile goal.
