### ISSUE TITLE
MathML (generated) — scripted property declaration in OPF

### ISSUE THREAD

**Issue by bdolor** [unit29868/pressbooks#40]
MathJax plugins have been used and tested on our instance for a while. We've settled with LaTeX for WordPress which handles MathML, despite its name. The commonality is that they all use MathJax, which is widely used. 

After the export routine you're likely to see something like this in the body of the xhtml file: 

`<script type="math/tex">E=mc^2</script>`
or
`<script type="math/tex">\displaystyle \int_1^2 \{x^2 + 1\} dx = \left[ \frac{x^3}{3} + x \right]_1^2</script>`

and this error in the debug console: 

 `ERROR: /Users/bpayne/Sites/pressbooks/wp-content/blogs.dir/7/files/exports/Testing-the-import-feature-1387231579._3.epub/OEBPS/chapter-001-chapter-1.xhtml: This file should declare in the OPF the property: scripted`

A routine that verifies any script tags (in the DOM) and appends a `properties="scripted"` attribute to the `<item>` element in the `<manifest>` is required. For example:

`<item id="chapter-001" href="OEBPS/chapter-001-chapter-1.xhtml" media-type="application/xhtml+xml" properties="scripted"/>`

**Comment by unit29868** [comment]
A solution has been implemented for this issue.
