### ISSUE TITLE
MathML and htmlawed

### ISSUE THREAD

**Issue by bdolor** [unit29868/pressbooks#41]
In order to get past htmlawed, MathML markup, herein considered non valid xhtml, needs to be converted to 'mixed markup' to pass htmlawed, then converted back on the other side. 

more detailed information here: 

http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawed_README.htm#s3.9

**Comment by unit29868** [comment]
Thanks for pointing me in this direction Brad. I'll implement something like this and see how it works.

**Comment by unit29868** [comment]
Courtesy update: I implemented an encode/decode method as described in @bdolor link above. HTMLawed is still mangling the resulting output somehow. When I comment out Htmlawed the encode/decode routine into an export works and appears fine when viewing in a reader. Comment it back in and portions of the MathML structure get mangled and the surrounding title text along with break tags are being culled out. I'll have to play around with it and see if I can stumble into the reason why this is occurring.

**Comment by unit29868** [comment]
Closing this issue, as a solution has been implemented.
